### ISSUE TITLE
一直刷新页面

### ISSUE THREAD

**Issue by lonzoen** [Bleu404/ThunderPanLink#1]
点击直链，一直提示请重新刷新页面
<img width="552" alt="image" src="https://user-images.githubusercontent.com/22364270/189350653-f85f2072-3355-47c7-89c9-97c848a953a7.png">

**Comment by Bleu404** [comment]
什么浏览器

**Comment by lonzoen** [comment]
Chrome最新版105

**Comment by Bleu404** [comment]
我这边测试刷新完页面是能用的

**Comment by lonzoen** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/22364270/189358583-4bbe816f-3079-4714-8918-f5acf01e5375.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/22364270/189358658-8fcd8dbd-ce62-4cac-b335-0f7d51780a20.png">

**Comment by Bleu404** [comment]
你这应该是违规资源吧
